import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Aboutus from './Aboutus'
import ContactUs from './contactUs'
import HomePage from './HomePage'
import MeetOurTeam from './MeetOurTeam'
import Services from './Services'
import Testimonials from './Testimonials'


export default function Home() {
  return (
    < >
      <Head>
        <title>sERVYCER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{/*
 <HomePage />
      <Services />
      <Aboutus />
      <MeetOurTeam />
     <Testimonials />

*/}
<ContactUs />

    </>
  )
}
